### ISSUE TITLE
Jenifer Riggins: Note down chapter timestamps for audio clips and YouTube

### ISSUE THREAD

**Issue by schalkneethling** [mechanical-ink/mechanical-ink-podcast#52]
https://drive.google.com/drive/folders/1LvWLm0QvwKlMGMdK-KbGeKG4VeYlX4Qf?usp=drive_link

YouTube: https://youtu.be/oC6F4RZnDLs?si=2P2CFbBDjHtqzZmx

- [x] Note down chapter timestamps for audio clips and YouTube

**Comment by schalkneethling** [comment]
@RingDangDoo How is this one coming along? I also added a link to the episode on YouTube if that would be helpful. Thanks.

**Comment by schalkneethling** [comment]
@RingDangDoo friendly ping for the timestamps.

**Comment by RingDangDoo** [comment]
@schalkneethling Here are the time stamps for Jenifer Riggins

00:00:00 - 00:04:40 - Intro
00:04:40 - 00:19:30 - What is an open source company?
00:19:30 - 00:20:40 - Audacity
00:20:30 - 00:23:50 - Forking WordPress and technical debt
00:23:50 - 00:27:55 - Raise issues
00:27:55 - 00:32:40 - Mozilla
00:32:40 - 00:37:22 - Invest in staff and code of conduct
00:37:22 - 00:42:40 - Community/Contributor problems
00:42:40 - 00:45:05 - Microsoft and diverse engineers
00:45:05 - 00:51:10 - Layoffs and being overstaffed
00:51:10 - 00:54:45 - Loadshedding and accessibility 
00:54:45 - 00:56:17 - In Closing

**Comment by schalkneethling** [comment]
> @schalkneethling Here are the time stamps for Jenifer Riggins
> 
> 00:00:00 - 00:04:40 - Intro 00:04:40 - 00:19:30 - What is an open source company? 00:19:30 - 00:20:40 - Audacity 00:20:30 - 00:23:50 - Forking WordPress and technical debt 00:23:50 - 00:27:55 - Raise issues 00:27:55 - 00:32:40 - Mozilla 00:32:40 - 00:37:22 - Invest in staff and code of conduct 00:37:22 - 00:42:40 - Community/Contributor problems 00:42:40 - 00:45:05 - Microsoft and diverse engineers 00:45:05 - 00:51:10 - Layoffs and being overstaffed 00:51:10 - 00:54:45 - Loadshedding and accessibility 00:54:45 - 00:56:17 - In Closing

This looks great! Thanks.

**Comment by schalkneethling** [comment]
@RingDangDoo They are live! You can also simplify the above to the following:

```
00:04:40 - What is an open-source company?
00:19:30 - Audacity
00:20:30 - Forking WordPress and technical debt
00:23:50 - Raise issues
00:27:55 - Mozilla
00:32:40 - Invest in staff and code of conduct
00:37:22 - Community/Contributor problems
00:42:40 - Microsoft and diverse engineers
00:45:05 - Layoffs and being overstaffed
00:51:10] - Loadshedding and accessibility
00:54:45 - In Closing
```

We can probably also drop the "Intro". What I _do_ like to do is have a chapter that starts where the guest introduce themselves. I call this something like, "Jenifer Riggins #whoami"
